package app.travelaround.common.error;

public enum ErrorCode {
    VALIDATION_ERROR,
    LOCATION_REQUIRED,
    CHECK_IN_OUT_OF_RANGE,
    AUTH_REQUIRED,
    FORBIDDEN,
    USER_NOT_FOUND,
    CITY_NOT_FOUND,
    SPOT_NOT_FOUND,
    TRIP_NOT_FOUND,
    PLAN_NOT_FOUND,
    IMAGE_NOT_FOUND,
    AI_MEMORY_NOT_FOUND,
    COMMUNITY_POST_NOT_FOUND,
    DUPLICATE_RESOURCE,
    TRIP_DATE_CONFLICT,
    AI_MEMORY_NOT_READY,
    RATE_LIMITED,
    INTERNAL_ERROR
}
